# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitPromptStory < Formula
  desc "Git commit prompt generator using AI to create meaningful commit messages"
  homepage "https://github.com/QuesmaOrg/git-prompt-story"
  version "0.15.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/QuesmaOrg/git-prompt-story/releases/download/v0.15.3/git-prompt-story_darwin_amd64.tar.gz"
      sha256 "06a280a2ddfcf66555cf58e60544059dfd91dca8a8dca43678a2129e37a7c5e7"

      def install
        bin.install "git-prompt-story"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/QuesmaOrg/git-prompt-story/releases/download/v0.15.3/git-prompt-story_darwin_arm64.tar.gz"
      sha256 "3684d27c4c01b3e33182d6a8dbf9359d646a71fc34c97542bb4fed611d20bc38"

      def install
        bin.install "git-prompt-story"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/QuesmaOrg/git-prompt-story/releases/download/v0.15.3/git-prompt-story_linux_amd64.tar.gz"
      sha256 "8074494e3f43027425efdaab8ed37313f068e9a42b7fabfe8f6e5f0bbfe7a05c"
      def install
        bin.install "git-prompt-story"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/QuesmaOrg/git-prompt-story/releases/download/v0.15.3/git-prompt-story_linux_arm64.tar.gz"
      sha256 "a973330965babefa20e89b67b393ccba8ccc1fab11d6eb7dc193337a7318fb7a"
      def install
        bin.install "git-prompt-story"
      end
    end
  end
end
